[2024-01-30T07:26:06.427+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: downloading_fundamentals.caluclating_gross_margin scheduled__2024-01-29T00:00:00+00:00 [queued]>
[2024-01-30T07:26:06.440+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: downloading_fundamentals.caluclating_gross_margin scheduled__2024-01-29T00:00:00+00:00 [queued]>
[2024-01-30T07:26:06.441+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-30T07:26:06.463+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): caluclating_gross_margin> on 2024-01-29 00:00:00+00:00
[2024-01-30T07:26:06.471+0000] {standard_task_runner.py:57} INFO - Started process 78 to run task
[2024-01-30T07:26:06.477+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'downloading_fundamentals', 'caluclating_gross_margin', 'scheduled__2024-01-29T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmpof6u83r3']
[2024-01-30T07:26:06.483+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask caluclating_gross_margin
[2024-01-30T07:26:06.563+0000] {task_command.py:416} INFO - Running <TaskInstance: downloading_fundamentals.caluclating_gross_margin scheduled__2024-01-29T00:00:00+00:00 [running]> on host c7ab13dc72cf
[2024-01-30T07:26:06.733+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@gmail.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='downloading_fundamentals' AIRFLOW_CTX_TASK_ID='caluclating_gross_margin' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-29T00:00:00+00:00'
[2024-01-30T07:26:07.020+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 64, in get_gross_margin
    spark = (SparkSession.builder
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2024-01-30T07:26:07.078+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=downloading_fundamentals, task_id=caluclating_gross_margin, execution_date=20240129T000000, start_date=20240130T072606, end_date=20240130T072607
[2024-01-30T07:26:07.160+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 65 for task caluclating_gross_margin ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 78)
[2024-01-30T07:26:07.187+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-30T07:26:07.226+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
