[2024-02-01T13:02:58.912+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: calculating_gross_margin.sending_email manual__2024-02-01T13:02:30.616028+00:00 [queued]>
[2024-02-01T13:02:58.919+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: calculating_gross_margin.sending_email manual__2024-02-01T13:02:30.616028+00:00 [queued]>
[2024-02-01T13:02:58.920+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-02-01T13:02:58.932+0000] {taskinstance.py:1382} INFO - Executing <Task(EmailOperator): sending_email> on 2024-02-01 13:02:30.616028+00:00
[2024-02-01T13:02:58.939+0000] {standard_task_runner.py:57} INFO - Started process 313 to run task
[2024-02-01T13:02:58.942+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'calculating_gross_margin', 'sending_email', 'manual__2024-02-01T13:02:30.616028+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmpp84dyq7o']
[2024-02-01T13:02:58.948+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask sending_email
[2024-02-01T13:02:58.998+0000] {task_command.py:416} INFO - Running <TaskInstance: calculating_gross_margin.sending_email manual__2024-02-01T13:02:30.616028+00:00 [running]> on host d7da08e2df39
[2024-02-01T13:02:59.066+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@outlook.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='calculating_gross_margin' AIRFLOW_CTX_TASK_ID='sending_email' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T13:02:30.616028+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-01T13:02:30.616028+00:00'
[2024-02-01T13:02:59.077+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-02-01T13:02:59.078+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-02-01T13:02:59.776+0000] {email.py:281} INFO - Sent an alert email to ['gerardchurch133@outlook.com']
[2024-02-01T13:03:00.159+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 77, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 282, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/local/lib/python3.8/smtplib.py", line 906, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (554, b'5.2.252 SendAsDenied; gerardchurch133@outlook.com not allowed to send as airflow@example.com; STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message [BeginDiagnosticData]Cannot submit message. 0.35250:1C040000, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:BC340000, 1.36674:0E000000, 1.61250:00000000, 1.45378:C1340000, 1.44866:6C010000, 16.55847:44120000, 17.43559:0000000024020000000000000000000000000000, 20.52176:140F519C1900001000000000, 20.50032:140F519C8917F01F56000000, 0.53414:14004A67, 0.35180:00000000, 255.23226:09000000, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A004967, 0.35250:140F519C, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:74000000, 1.36674:32000000, 1.61250:00000000, 1.45378:79000000, 1.44866:01000000, 16.55847:EF000000, 17.43559:00000000B8030000000000000000000000000000, 20.52176:140F519C190070201400FE67, 20.50032:140F519C8917101065040000, 0.53414:0B004536, 0.35180:03004E67, 255.23226:6E040000, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:80030400, 4.21921:DC040000, 255.27962:FA000000, 255.1494:0A000910, 0.38698:05000780, 1.41134:47000000, 0.37692:87000000, 0.37948:87000000, 5.33852:00000000534D545000000000, 7.36354:0100000000000109460EBD6A, 4.56248:DC040000, 7.40748:010000000000010B03000000, 7.57132:00000000000000003608C700, 4.39640:DC040000, 1.63016:32000000, 8.45434:FDBF0300AC7357BE00000000000000003A353161, 1.46798:04000000, 5.10786:0000000031352E32302E373234392E3032353A444239503139334D42313834393A35316132656334362D323235642D346665642D396135342D6232383939656561643063393A39393632343A2E4E455420362E302E32360000000000, 7.51330:85468C1F2623DC0800000000, 0.39570:12000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 1.33010:32000000, 2.54258:DC040000, 255.1750:0300BC3D, 255.31418:DD020000, 0.22753:0A009510, 255.21817:DC040000, 0.64418:E2020000, 4.39842:DC040000, 0.41586:03009B0E, 4.60547:DC040000, 0.21966:0A009610, 4.30158:DC040000[EndDiagnosticData] [Hostname=DB9P193MB1849.EURP193.PROD.OUTLOOK.COM]')
[2024-02-01T13:03:00.176+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=calculating_gross_margin, task_id=sending_email, execution_date=20240201T130230, start_date=20240201T130258, end_date=20240201T130300
[2024-02-01T13:03:00.189+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 147 for task sending_email ((554, b'5.2.252 SendAsDenied; gerardchurch133@outlook.com not allowed to send as airflow@example.com; STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message [BeginDiagnosticData]Cannot submit message. 0.35250:1C040000, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:BC340000, 1.36674:0E000000, 1.61250:00000000, 1.45378:C1340000, 1.44866:6C010000, 16.55847:44120000, 17.43559:0000000024020000000000000000000000000000, 20.52176:140F519C1900001000000000, 20.50032:140F519C8917F01F56000000, 0.53414:14004A67, 0.35180:00000000, 255.23226:09000000, 255.27962:0A000000, 255.27962:0E000000, 255.31418:0A004967, 0.35250:140F519C, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:74000000, 1.36674:32000000, 1.61250:00000000, 1.45378:79000000, 1.44866:01000000, 16.55847:EF000000, 17.43559:00000000B8030000000000000000000000000000, 20.52176:140F519C190070201400FE67, 20.50032:140F519C8917101065040000, 0.53414:0B004536, 0.35180:03004E67, 255.23226:6E040000, 255.27962:0A000000, 255.27962:32000000, 255.17082:DC040000, 0.27745:80030400, 4.21921:DC040000, 255.27962:FA000000, 255.1494:0A000910, 0.38698:05000780, 1.41134:47000000, 0.37692:87000000, 0.37948:87000000, 5.33852:00000000534D545000000000, 7.36354:0100000000000109460EBD6A, 4.56248:DC040000, 7.40748:010000000000010B03000000, 7.57132:00000000000000003608C700, 4.39640:DC040000, 1.63016:32000000, 8.45434:FDBF0300AC7357BE00000000000000003A353161, 1.46798:04000000, 5.10786:0000000031352E32302E373234392E3032353A444239503139334D42313834393A35316132656334362D323235642D346665642D396135342D6232383939656561643063393A39393632343A2E4E455420362E302E32360000000000, 7.51330:85468C1F2623DC0800000000, 0.39570:12000000, 1.55954:0A000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.33010:0A000000, 2.54258:00000000, 0.40002:00000000, 1.56562:00000000, 1.64146:32000000, 1.33010:32000000, 2.54258:DC040000, 1.33010:32000000, 2.54258:DC040000, 255.1750:0300BC3D, 255.31418:DD020000, 0.22753:0A009510, 255.21817:DC040000, 0.64418:E2020000, 4.39842:DC040000, 0.41586:03009B0E, 4.60547:DC040000, 0.21966:0A009610, 4.30158:DC040000[EndDiagnosticData] [Hostname=DB9P193MB1849.EURP193.PROD.OUTLOOK.COM]'); 313)
[2024-02-01T13:03:00.200+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-01T13:03:00.216+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
