[2024-02-01T09:38:43.764+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: calculating_gross_margin.checking_api_for_data manual__2024-02-01T09:38:38.472508+00:00 [queued]>
[2024-02-01T09:38:43.774+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: calculating_gross_margin.checking_api_for_data manual__2024-02-01T09:38:38.472508+00:00 [queued]>
[2024-02-01T09:38:43.775+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-02-01T09:38:43.787+0000] {taskinstance.py:1382} INFO - Executing <Task(HttpSensor): checking_api_for_data> on 2024-02-01 09:38:38.472508+00:00
[2024-02-01T09:38:43.792+0000] {standard_task_runner.py:57} INFO - Started process 249 to run task
[2024-02-01T09:38:43.795+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'calculating_gross_margin', 'checking_api_for_data', 'manual__2024-02-01T09:38:38.472508+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmpo1pgmez1']
[2024-02-01T09:38:43.798+0000] {standard_task_runner.py:85} INFO - Job 111: Subtask checking_api_for_data
[2024-02-01T09:38:43.845+0000] {task_command.py:416} INFO - Running <TaskInstance: calculating_gross_margin.checking_api_for_data manual__2024-02-01T09:38:38.472508+00:00 [running]> on host 3dac598680fc
[2024-02-01T09:38:43.908+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@outlook.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='calculating_gross_margin' AIRFLOW_CTX_TASK_ID='checking_api_for_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T09:38:38.472508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-01T09:38:38.472508+00:00'
[2024-02-01T09:38:43.909+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T09:38:43.917+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T09:38:45.584+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': 'b1aa416c-c0e5-11ee-bb3f-0242ac120004'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:38:45 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T09:38:45.701+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '554afe1c-b002-001d-29f2-548d92000000'
    'x-ms-client-request-id': 'b1aa416c-c0e5-11ee-bb3f-0242ac120004'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:38:47 GMT'
[2024-02-01T09:39:45.717+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T09:39:45.741+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T09:39:47.042+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': 'd64c3084-c0e5-11ee-bb3f-0242ac120004'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:39:47 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T09:39:47.193+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5b3c8756-6002-0043-6ff2-546672000000'
    'x-ms-client-request-id': 'd64c3084-c0e5-11ee-bb3f-0242ac120004'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:39:49 GMT'
[2024-02-01T09:40:47.259+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T09:40:47.275+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T09:40:49.330+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': 'fb6c84e0-c0e5-11ee-bb3f-0242ac120004'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:40:49 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T09:40:49.505+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'f82d940e-5002-0077-4cf2-5455ba000000'
    'x-ms-client-request-id': 'fb6c84e0-c0e5-11ee-bb3f-0242ac120004'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:40:51 GMT'
[2024-02-01T09:41:49.565+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T09:41:49.572+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T09:41:54.187+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': '2214ead8-c0e6-11ee-bb3f-0242ac120004'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:41:54 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T09:41:54.377+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'b1445165-0002-0037-63f2-545282000000'
    'x-ms-client-request-id': '2214ead8-c0e6-11ee-bb3f-0242ac120004'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:41:55 GMT'
[2024-02-01T09:42:54.434+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T09:42:54.441+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T09:42:55.764+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': '46c8de0c-c0e6-11ee-bb3f-0242ac120004'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:42:55 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T09:42:55.900+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '1a1bc108-b002-008b-64f3-548443000000'
    'x-ms-client-request-id': '46c8de0c-c0e6-11ee-bb3f-0242ac120004'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:42:57 GMT'
[2024-02-01T09:43:55.964+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T09:43:55.971+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T09:43:58.415+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': '6c20ae5a-c0e6-11ee-bb3f-0242ac120004'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:43:58 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T09:43:58.551+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '19b8f7d5-4002-0019-23f3-540095000000'
    'x-ms-client-request-id': '6c20ae5a-c0e6-11ee-bb3f-0242ac120004'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 09:44:00 GMT'
[2024-02-01T09:43:58.556+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 314.64481590000014 seconds exceeds the specified timeout of 300.0.
[2024-02-01T09:43:58.565+0000] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=calculating_gross_margin, task_id=checking_api_for_data, execution_date=20240201T093838, start_date=20240201T093843, end_date=20240201T094358
[2024-02-01T09:43:58.578+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-02-01T09:43:58.579+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-02-01T09:43:58.580+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-02-01T09:43:58.586+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-02-01T09:43:58.587+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-02-01T09:43:58.588+0000] {taskinstance.py:2007} ERROR - Failed to send email to: gerardchurch133@outlook.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 314.64481590000014 seconds exceeds the specified timeout of 300.0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-02-01T09:43:58.606+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 111 for task checking_api_for_data (Sensor has timed out; run duration of 314.64481590000014 seconds exceeds the specified timeout of 300.0.; 249)
[2024-02-01T09:43:58.652+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-01T09:43:58.681+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
