[2024-02-01T10:43:53.408+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: calculating_gross_margin.checking_api_for_data manual__2024-02-01T10:43:46.939712+00:00 [queued]>
[2024-02-01T10:43:53.417+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: calculating_gross_margin.checking_api_for_data manual__2024-02-01T10:43:46.939712+00:00 [queued]>
[2024-02-01T10:43:53.417+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-02-01T10:43:53.428+0000] {taskinstance.py:1382} INFO - Executing <Task(HttpSensor): checking_api_for_data> on 2024-02-01 10:43:46.939712+00:00
[2024-02-01T10:43:53.433+0000] {standard_task_runner.py:57} INFO - Started process 505 to run task
[2024-02-01T10:43:53.436+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'calculating_gross_margin', 'checking_api_for_data', 'manual__2024-02-01T10:43:46.939712+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmpqez5qh7s']
[2024-02-01T10:43:53.439+0000] {standard_task_runner.py:85} INFO - Job 125: Subtask checking_api_for_data
[2024-02-01T10:43:53.485+0000] {task_command.py:416} INFO - Running <TaskInstance: calculating_gross_margin.checking_api_for_data manual__2024-02-01T10:43:46.939712+00:00 [running]> on host cd150dcb29cf
[2024-02-01T10:43:53.571+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@outlook.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='calculating_gross_margin' AIRFLOW_CTX_TASK_ID='checking_api_for_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T10:43:46.939712+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-01T10:43:46.939712+00:00'
[2024-02-01T10:43:53.572+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T10:43:53.581+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T10:43:55.671+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': 'cc423012-c0ee-11ee-a013-0242ac140005'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:43:55 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T10:43:55.790+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '2621757e-d002-0069-38fb-54b962000000'
    'x-ms-client-request-id': 'cc423012-c0ee-11ee-a013-0242ac140005'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:43:57 GMT'
[2024-02-01T10:44:55.855+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T10:44:55.862+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T10:44:58.477+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': 'f1b1c4e8-c0ee-11ee-a013-0242ac140005'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:44:58 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T10:44:58.602+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '0721742f-3002-002c-25fb-546c81000000'
    'x-ms-client-request-id': 'f1b1c4e8-c0ee-11ee-a013-0242ac140005'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:45:00 GMT'
[2024-02-01T10:45:58.666+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T10:45:58.675+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T10:46:00.381+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': '169789fa-c0ef-11ee-a013-0242ac140005'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:46:00 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T10:46:00.504+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '4e279a56-8002-0080-24fb-547f28000000'
    'x-ms-client-request-id': '169789fa-c0ef-11ee-a013-0242ac140005'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:46:02 GMT'
[2024-02-01T10:47:00.560+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T10:47:00.568+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T10:47:02.498+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': '3b9ded34-c0ef-11ee-a013-0242ac140005'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:47:02 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T10:47:02.626+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '5551120a-b002-001d-19fb-548d92000000'
    'x-ms-client-request-id': '3b9ded34-c0ef-11ee-a013-0242ac140005'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:47:04 GMT'
[2024-02-01T10:48:02.690+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T10:48:02.697+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T10:48:04.158+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': '605e6dec-c0ef-11ee-a013-0242ac140005'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:48:04 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T10:48:04.282+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': '04aff745-4002-0009-15fc-54c5fd000000'
    'x-ms-client-request-id': '605e6dec-c0ef-11ee-a013-0242ac140005'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:48:05 GMT'
[2024-02-01T10:49:04.344+0000] {http.py:130} INFO - Poking: symbols/get-financials
[2024-02-01T10:49:04.351+0000] {base.py:73} INFO - Using connection ID 'rapid_api' for task execution.
[2024-02-01T10:49:05.761+0000] {_universal.py:514} INFO - Request URL: 'https://datalakeuksouth2311.table.core.windows.net/fundamentalsraw()?$filter=REDACTED'
Request method: 'GET'
Request headers:
    'x-ms-version': 'REDACTED'
    'DataServiceVersion': 'REDACTED'
    'Accept': 'application/json;odata=minimalmetadata'
    'x-ms-client-request-id': '85164eca-c0ef-11ee-a013-0242ac140005'
    'x-ms-date': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:49:05 GMT'
    'User-Agent': 'azsdk-python-data-tables/12.5.0 Python/3.8.18 (Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5)'
    'Authorization': 'REDACTED'
No body was attached to the request
[2024-02-01T10:49:05.883+0000] {_universal.py:550} INFO - Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Transfer-Encoding': 'chunked'
    'Content-Type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8'
    'Server': 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0'
    'x-ms-request-id': 'a8b3d431-9002-0047-28fc-54eb75000000'
    'x-ms-client-request-id': '85164eca-c0ef-11ee-a013-0242ac140005'
    'x-ms-version': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Thu, 01 Feb 2024 10:49:08 GMT'
[2024-02-01T10:49:05.888+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 312.31561799999963 seconds exceeds the specified timeout of 300.0.
[2024-02-01T10:49:05.896+0000] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=calculating_gross_margin, task_id=checking_api_for_data, execution_date=20240201T104346, start_date=20240201T104353, end_date=20240201T104905
[2024-02-01T10:49:05.906+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-02-01T10:49:05.907+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-02-01T10:49:05.907+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-02-01T10:49:05.913+0000] {configuration.py:1050} WARNING - section/key [smtp/smtp_user] not found in config
[2024-02-01T10:49:05.914+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-02-01T10:49:05.915+0000] {taskinstance.py:2007} ERROR - Failed to send email to: gerardchurch133@outlook.com
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1518, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1681, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1744, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 312.31561799999963 seconds exceeds the specified timeout of 300.0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2420, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2005, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2422, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-02-01T10:49:05.931+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 125 for task checking_api_for_data (Sensor has timed out; run duration of 312.31561799999963 seconds exceeds the specified timeout of 300.0.; 505)
[2024-02-01T10:49:05.945+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-02-01T10:49:05.966+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
