[2024-01-06T19:48:55.868+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: downloading_fundamentals.downloading_fundamentals manual__2024-01-06T19:48:54.112637+00:00 [queued]>
[2024-01-06T19:48:55.876+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: downloading_fundamentals.downloading_fundamentals manual__2024-01-06T19:48:54.112637+00:00 [queued]>
[2024-01-06T19:48:55.877+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-06T19:48:55.889+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): downloading_fundamentals> on 2024-01-06 19:48:54.112637+00:00
[2024-01-06T19:48:55.894+0000] {standard_task_runner.py:57} INFO - Started process 75 to run task
[2024-01-06T19:48:55.897+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'downloading_fundamentals', 'downloading_fundamentals', 'manual__2024-01-06T19:48:54.112637+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/fundamental_data_pipeline.py', '--cfg-path', '/tmp/tmpxgvlg_f_']
[2024-01-06T19:48:55.901+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask downloading_fundamentals
[2024-01-06T19:48:55.950+0000] {task_command.py:416} INFO - Running <TaskInstance: downloading_fundamentals.downloading_fundamentals manual__2024-01-06T19:48:54.112637+00:00 [running]> on host 028d52c20d97
[2024-01-06T19:48:56.015+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gerardchurch133@gmail.com' AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='downloading_fundamentals' AIRFLOW_CTX_TASK_ID='downloading_fundamentals' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T19:48:54.112637+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-06T19:48:54.112637+00:00'
[2024-01-06T19:48:56.017+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 15, in get_fundamental_data
    headers = {"X-RapidAPI-Key": os.environ['rapidapi_key'],
  File "/usr/local/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'rapidapi_key'
[2024-01-06T19:48:56.375+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=downloading_fundamentals, task_id=downloading_fundamentals, execution_date=20240106T194854, start_date=20240106T194855, end_date=20240106T194856
[2024-01-06T19:48:56.389+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task downloading_fundamentals ('rapidapi_key'; 75)
[2024-01-06T19:48:56.432+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-06T19:48:56.447+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
