[2023-12-07T09:23:24.087+0000] {processor.py:157} INFO - Started process (PID=3127) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:23:24.096+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:23:24.112+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:23:24.111+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:23:24.266+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:23:24.245+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:23:24.275+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:23:24.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.427 seconds
[2023-12-07T09:23:55.581+0000] {processor.py:157} INFO - Started process (PID=3135) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:23:55.590+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:23:55.632+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:23:55.630+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:23:55.775+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:23:55.757+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:23:55.779+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:23:56.229+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.723 seconds
[2023-12-07T09:24:26.710+0000] {processor.py:157} INFO - Started process (PID=3143) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:24:26.717+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:24:26.750+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:24:26.747+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:24:26.822+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:24:26.807+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:24:26.825+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:24:26.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.298 seconds
[2023-12-07T09:24:57.152+0000] {processor.py:157} INFO - Started process (PID=3151) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:24:57.153+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:24:57.155+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:24:57.155+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:24:57.184+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:24:57.179+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:24:57.186+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:24:57.205+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.057 seconds
[2023-12-07T09:25:27.327+0000] {processor.py:157} INFO - Started process (PID=3159) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:25:27.328+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:25:27.331+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:25:27.331+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:25:27.363+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:25:27.357+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:25:27.366+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:25:27.388+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.064 seconds
[2023-12-07T09:25:57.536+0000] {processor.py:157} INFO - Started process (PID=3167) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:25:57.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:25:57.541+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:25:57.541+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:25:57.568+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:25:57.562+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:25:57.569+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:25:57.591+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.058 seconds
[2023-12-07T09:26:27.722+0000] {processor.py:157} INFO - Started process (PID=3175) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:26:27.723+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:26:27.726+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:26:27.726+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:26:27.752+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:26:27.747+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:26:27.753+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:26:27.773+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.054 seconds
[2023-12-07T09:26:57.913+0000] {processor.py:157} INFO - Started process (PID=3183) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:26:57.915+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:26:57.917+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:26:57.917+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:26:57.942+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:26:57.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:26:57.943+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:26:57.961+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-07T09:27:28.102+0000] {processor.py:157} INFO - Started process (PID=3191) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:27:28.103+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:27:28.106+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:27:28.106+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:27:28.131+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:27:28.126+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:27:28.132+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:27:28.150+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-07T09:27:58.291+0000] {processor.py:157} INFO - Started process (PID=3199) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:27:58.292+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:27:58.295+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:27:58.295+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:27:58.319+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:27:58.314+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:27:58.321+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:27:58.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-07T09:28:28.548+0000] {processor.py:157} INFO - Started process (PID=3207) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:28:28.549+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:28:28.552+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:28:28.552+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:28:28.581+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:28:28.575+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:28:28.582+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:28:28.602+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.057 seconds
[2023-12-07T09:28:58.729+0000] {processor.py:157} INFO - Started process (PID=3215) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:28:58.730+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:28:58.732+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:28:58.732+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:28:58.757+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:28:58.752+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:28:58.759+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:28:58.777+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-07T09:29:28.935+0000] {processor.py:157} INFO - Started process (PID=3223) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:29:28.936+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:29:28.939+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:29:28.939+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:29:28.968+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:29:28.962+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:29:28.969+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:29:28.987+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.056 seconds
[2023-12-07T09:29:59.115+0000] {processor.py:157} INFO - Started process (PID=3231) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:29:59.117+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:29:59.119+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:29:59.119+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:29:59.142+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:29:59.138+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:29:59.144+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:29:59.161+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-07T09:30:29.319+0000] {processor.py:157} INFO - Started process (PID=3239) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:30:29.320+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:30:29.322+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:30:29.322+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:30:29.350+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:30:29.344+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:30:29.351+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:30:29.370+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.054 seconds
[2023-12-07T09:30:59.490+0000] {processor.py:157} INFO - Started process (PID=3247) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:30:59.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:30:59.493+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:30:59.493+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:30:59.521+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:30:59.516+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:30:59.522+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:30:59.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-07T09:31:29.697+0000] {processor.py:157} INFO - Started process (PID=3255) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:31:29.698+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:31:29.701+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:31:29.701+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:31:29.729+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:31:29.723+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:31:29.730+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:31:29.749+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.054 seconds
[2023-12-07T09:31:59.882+0000] {processor.py:157} INFO - Started process (PID=3263) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:31:59.884+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:31:59.887+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:31:59.887+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:31:59.912+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:31:59.907+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:31:59.913+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:31:59.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-07T09:32:30.088+0000] {processor.py:157} INFO - Started process (PID=3271) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:32:30.090+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:32:30.093+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:32:30.092+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:32:30.128+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:32:30.121+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:32:30.131+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:32:30.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.068 seconds
[2023-12-07T09:33:00.252+0000] {processor.py:157} INFO - Started process (PID=3279) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:33:00.253+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:33:00.256+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:33:00.256+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:33:00.286+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:33:00.281+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:33:00.288+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:33:00.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.060 seconds
[2023-12-07T09:33:30.517+0000] {processor.py:157} INFO - Started process (PID=3287) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:33:30.518+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:33:30.521+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:33:30.521+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:33:30.554+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:33:30.549+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:33:30.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:33:30.574+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.060 seconds
[2023-12-07T09:34:00.700+0000] {processor.py:157} INFO - Started process (PID=3295) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:34:00.701+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:34:00.704+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:34:00.704+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:34:00.730+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:34:00.725+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:34:00.732+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:34:00.751+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.055 seconds
[2023-12-07T09:34:30.915+0000] {processor.py:157} INFO - Started process (PID=3303) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:34:30.916+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:34:30.918+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:34:30.918+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:34:30.946+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:34:30.940+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:34:30.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:34:30.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.055 seconds
[2023-12-07T09:35:01.093+0000] {processor.py:157} INFO - Started process (PID=3311) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:35:01.095+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:35:01.097+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:35:01.097+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:35:01.124+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:35:01.120+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:35:01.126+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:35:01.146+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.056 seconds
[2023-12-07T09:35:31.305+0000] {processor.py:157} INFO - Started process (PID=3319) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:35:31.306+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:35:31.308+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:35:31.308+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:35:31.336+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:35:31.331+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:35:31.338+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:35:31.355+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.053 seconds
[2023-12-07T09:36:01.483+0000] {processor.py:157} INFO - Started process (PID=3327) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:36:01.484+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:36:01.486+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:36:01.486+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:36:01.514+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:36:01.509+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:36:01.516+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:36:01.534+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.054 seconds
[2023-12-07T09:36:31.687+0000] {processor.py:157} INFO - Started process (PID=3335) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:36:31.688+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:36:31.690+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:36:31.690+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:36:31.716+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:36:31.711+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:36:31.717+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:36:31.738+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.054 seconds
[2023-12-07T09:37:01.856+0000] {processor.py:157} INFO - Started process (PID=3343) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:37:01.857+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:37:01.859+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:37:01.859+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:37:01.883+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:37:01.879+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:37:01.885+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:37:01.902+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-07T09:37:32.061+0000] {processor.py:157} INFO - Started process (PID=3351) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:37:32.062+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:37:32.065+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:37:32.065+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:37:32.088+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:37:32.083+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:37:32.090+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:37:32.108+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-07T09:38:02.223+0000] {processor.py:157} INFO - Started process (PID=3359) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:38:02.224+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:38:02.227+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:38:02.226+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:38:02.251+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:38:02.246+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:38:02.252+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:38:02.270+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-07T09:38:32.460+0000] {processor.py:157} INFO - Started process (PID=3367) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:38:32.461+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:38:32.464+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:38:32.464+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:38:32.487+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:38:32.482+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:38:32.488+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:38:32.505+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:39:02.627+0000] {processor.py:157} INFO - Started process (PID=3376) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:39:02.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:39:02.631+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:39:02.631+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:39:02.654+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:39:02.650+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:39:02.655+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:39:02.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:39:32.816+0000] {processor.py:157} INFO - Started process (PID=3384) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:39:32.817+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:39:32.819+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:39:32.819+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:39:32.841+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:39:32.837+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:39:32.842+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:39:32.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T09:40:02.999+0000] {processor.py:157} INFO - Started process (PID=3392) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:40:03.000+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:40:03.003+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:40:03.003+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:40:03.028+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:40:03.023+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:40:03.030+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:40:03.049+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.054 seconds
[2023-12-07T09:40:33.196+0000] {processor.py:157} INFO - Started process (PID=3400) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:40:33.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:40:33.200+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:40:33.199+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:40:33.222+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:40:33.218+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:40:33.224+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:40:33.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.097 seconds
[2023-12-07T09:41:03.371+0000] {processor.py:157} INFO - Started process (PID=3408) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:41:03.372+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:41:03.374+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:41:03.374+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:41:03.396+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:41:03.392+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:41:03.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:41:03.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:41:33.536+0000] {processor.py:157} INFO - Started process (PID=3416) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:41:33.537+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:41:33.539+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:41:33.539+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:41:33.563+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:41:33.559+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:41:33.565+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:41:33.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-07T09:42:03.727+0000] {processor.py:157} INFO - Started process (PID=3424) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:42:03.728+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:42:03.730+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:42:03.730+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:42:03.753+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:42:03.748+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:42:03.754+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:42:03.772+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:42:33.899+0000] {processor.py:157} INFO - Started process (PID=3432) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:42:33.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:42:33.903+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:42:33.902+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:42:33.924+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:42:33.919+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:42:33.925+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:42:33.942+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-07T09:43:04.088+0000] {processor.py:157} INFO - Started process (PID=3440) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:43:04.089+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:43:04.091+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:43:04.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:43:04.113+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:43:04.109+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:43:04.115+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:43:04.132+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T09:43:34.292+0000] {processor.py:157} INFO - Started process (PID=3448) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:43:34.293+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:43:34.295+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:43:34.295+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:43:34.319+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:43:34.315+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:43:34.321+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:43:34.340+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-07T09:44:04.459+0000] {processor.py:157} INFO - Started process (PID=3456) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:44:04.460+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:44:04.462+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:44:04.462+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:44:04.486+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:44:04.482+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:44:04.487+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:44:04.504+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:44:34.648+0000] {processor.py:157} INFO - Started process (PID=3464) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:44:34.649+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:44:34.652+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:44:34.651+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:44:34.675+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:44:34.670+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:44:34.676+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:44:34.694+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:45:04.814+0000] {processor.py:157} INFO - Started process (PID=3472) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:45:04.815+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:45:04.818+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:45:04.818+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:45:04.840+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:45:04.836+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:45:04.841+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:45:04.859+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:45:35.006+0000] {processor.py:157} INFO - Started process (PID=3480) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:45:35.007+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:45:35.009+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:45:35.009+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:45:35.034+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:45:35.029+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:45:35.035+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:45:35.053+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-07T09:46:05.168+0000] {processor.py:157} INFO - Started process (PID=3488) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:46:05.169+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:46:05.172+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:46:05.172+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:46:05.194+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:46:05.190+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:46:05.195+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:46:05.212+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T09:46:35.352+0000] {processor.py:157} INFO - Started process (PID=3496) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:46:35.353+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:46:35.359+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:46:35.359+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:46:35.392+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:46:35.387+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:46:35.393+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:46:35.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.064 seconds
[2023-12-07T09:47:05.520+0000] {processor.py:157} INFO - Started process (PID=3504) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:47:05.521+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:47:05.525+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:47:05.525+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:47:05.549+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:47:05.544+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:47:05.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:47:05.570+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.055 seconds
[2023-12-07T09:47:35.708+0000] {processor.py:157} INFO - Started process (PID=3512) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:47:35.709+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:47:35.711+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:47:35.711+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:47:35.733+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:47:35.729+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:47:35.734+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:47:35.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:48:05.875+0000] {processor.py:157} INFO - Started process (PID=3520) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:48:05.876+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:48:05.879+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:48:05.879+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:48:05.902+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:48:05.897+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:48:05.903+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:48:05.921+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:48:36.098+0000] {processor.py:157} INFO - Started process (PID=3528) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:48:36.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:48:36.101+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:48:36.100+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:48:36.122+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:48:36.118+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:48:36.123+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:48:36.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-07T09:49:06.273+0000] {processor.py:157} INFO - Started process (PID=3536) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:49:06.274+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:49:06.276+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:49:06.276+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:49:06.302+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:49:06.298+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:49:06.304+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:49:06.321+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-07T09:49:36.453+0000] {processor.py:157} INFO - Started process (PID=3544) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:49:36.455+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:49:36.458+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:49:36.457+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:49:36.479+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:49:36.475+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:49:36.481+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:49:36.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T09:50:06.636+0000] {processor.py:157} INFO - Started process (PID=3552) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:50:06.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:50:06.640+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:50:06.639+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:50:06.660+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:50:06.657+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:50:06.661+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:50:06.679+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-07T09:50:36.817+0000] {processor.py:157} INFO - Started process (PID=3560) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:50:36.818+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:50:36.821+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:50:36.821+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:50:36.844+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:50:36.840+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:50:36.846+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:50:36.863+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:51:06.998+0000] {processor.py:157} INFO - Started process (PID=3568) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:51:06.999+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:51:07.001+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:51:07.001+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:51:07.027+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:51:07.022+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:51:07.028+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:51:07.046+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-07T09:51:37.187+0000] {processor.py:157} INFO - Started process (PID=3576) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:51:37.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:51:37.191+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:51:37.191+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:51:37.218+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:51:37.213+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:51:37.219+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:51:37.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.055 seconds
[2023-12-07T09:52:07.368+0000] {processor.py:157} INFO - Started process (PID=3584) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:52:07.369+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:52:07.372+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:52:07.372+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:52:07.394+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:52:07.390+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:52:07.395+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:52:07.415+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.050 seconds
[2023-12-07T09:52:37.556+0000] {processor.py:157} INFO - Started process (PID=3592) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:52:37.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:52:37.560+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:52:37.559+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:52:37.579+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:52:37.576+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:52:37.580+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:52:37.597+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.044 seconds
[2023-12-07T09:53:07.720+0000] {processor.py:157} INFO - Started process (PID=3600) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:53:07.721+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:53:07.723+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:53:07.723+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:53:07.745+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:53:07.741+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:53:07.746+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:53:07.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T09:53:37.949+0000] {processor.py:157} INFO - Started process (PID=3608) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:53:37.950+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:53:37.952+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:53:37.952+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:53:37.976+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:53:37.970+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:53:37.977+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:53:38.000+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.054 seconds
[2023-12-07T09:54:08.110+0000] {processor.py:157} INFO - Started process (PID=3616) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:54:08.111+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:54:08.113+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:54:08.113+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:54:08.134+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:54:08.130+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:54:08.136+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:54:08.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-07T09:54:38.311+0000] {processor.py:157} INFO - Started process (PID=3624) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:54:38.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:54:38.315+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:54:38.314+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:54:38.338+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:54:38.334+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:54:38.339+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:54:38.357+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:55:08.474+0000] {processor.py:157} INFO - Started process (PID=3632) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:55:08.476+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:55:08.478+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:55:08.478+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:55:08.501+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:55:08.496+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:55:08.502+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:55:08.519+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T09:55:38.658+0000] {processor.py:157} INFO - Started process (PID=3640) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:55:38.659+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:55:38.661+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:55:38.661+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:55:38.681+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:55:38.678+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:55:38.683+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:55:38.700+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-07T09:56:08.822+0000] {processor.py:157} INFO - Started process (PID=3649) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:56:08.823+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:56:08.825+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:56:08.825+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:56:08.847+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:56:08.844+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:56:08.849+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:56:08.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T09:56:39.007+0000] {processor.py:157} INFO - Started process (PID=3657) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:56:39.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:56:39.010+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:56:39.010+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:56:39.034+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:56:39.030+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:56:39.035+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:56:39.052+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T09:57:09.174+0000] {processor.py:157} INFO - Started process (PID=3665) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:57:09.175+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:57:09.177+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:57:09.177+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:57:09.199+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:57:09.195+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:57:09.200+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:57:09.217+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T09:57:39.361+0000] {processor.py:157} INFO - Started process (PID=3673) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:57:39.362+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:57:39.365+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:57:39.365+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:57:39.387+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:57:39.383+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:57:39.389+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:57:39.407+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-07T09:58:09.530+0000] {processor.py:157} INFO - Started process (PID=3681) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:58:09.531+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:58:09.533+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:58:09.533+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:58:09.554+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:58:09.549+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:58:09.555+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:58:09.571+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-07T09:58:39.746+0000] {processor.py:157} INFO - Started process (PID=3689) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:58:39.747+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:58:39.750+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:58:39.749+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:58:39.772+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:58:39.767+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:58:39.773+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:58:39.790+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-07T09:59:09.914+0000] {processor.py:157} INFO - Started process (PID=3697) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:59:09.915+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:59:09.917+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:59:09.917+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:59:09.936+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:59:09.932+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:59:09.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:59:09.954+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.043 seconds
[2023-12-07T09:59:40.105+0000] {processor.py:157} INFO - Started process (PID=3705) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:59:40.107+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T09:59:40.109+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:59:40.108+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:59:40.132+0000] {logging_mixin.py:154} INFO - [2023-12-07T09:59:40.127+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T09:59:40.133+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T09:59:40.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T10:00:10.271+0000] {processor.py:157} INFO - Started process (PID=3713) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:00:10.272+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:00:10.274+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:00:10.274+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:00:10.296+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:00:10.292+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:00:10.298+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:00:10.315+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T10:00:40.450+0000] {processor.py:157} INFO - Started process (PID=3721) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:00:40.451+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:00:40.453+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:00:40.452+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:00:40.473+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:00:40.469+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:00:40.475+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:00:40.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-07T10:01:10.616+0000] {processor.py:157} INFO - Started process (PID=3729) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:01:10.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:01:10.619+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:01:10.619+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:01:10.642+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:01:10.638+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:01:10.644+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:01:10.661+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T10:01:40.800+0000] {processor.py:157} INFO - Started process (PID=3737) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:01:40.802+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:01:40.804+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:01:40.804+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:01:40.827+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:01:40.822+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:01:40.829+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:01:40.848+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-07T10:02:10.959+0000] {processor.py:157} INFO - Started process (PID=3745) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:02:10.961+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:02:10.963+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:02:10.963+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:02:10.985+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:02:10.981+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:02:10.986+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:02:11.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T10:02:41.142+0000] {processor.py:157} INFO - Started process (PID=3753) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:02:41.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:02:41.145+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:02:41.145+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:02:41.167+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:02:41.163+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:02:41.169+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:02:41.186+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T10:03:11.310+0000] {processor.py:157} INFO - Started process (PID=3761) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:03:11.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:03:11.313+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:03:11.313+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:03:11.335+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:03:11.331+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:03:11.336+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:03:11.355+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-07T10:03:41.521+0000] {processor.py:157} INFO - Started process (PID=3769) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:03:41.522+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:03:41.525+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:03:41.525+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:03:41.545+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:03:41.541+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:03:41.546+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:03:41.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-07T10:04:11.681+0000] {processor.py:157} INFO - Started process (PID=3777) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:04:11.682+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:04:11.685+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:04:11.685+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:04:11.708+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:04:11.704+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:04:11.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:04:11.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-07T10:04:41.864+0000] {processor.py:157} INFO - Started process (PID=3785) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:04:41.865+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:04:41.867+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:04:41.867+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:04:41.887+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:04:41.884+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:04:41.889+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:04:41.906+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.045 seconds
[2023-12-07T10:05:12.036+0000] {processor.py:157} INFO - Started process (PID=3793) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:05:12.037+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:05:12.039+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:05:12.039+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:05:12.063+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:05:12.058+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:05:12.065+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:05:12.082+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.049 seconds
[2023-12-07T10:05:42.219+0000] {processor.py:157} INFO - Started process (PID=3801) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:05:42.220+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:05:42.223+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:05:42.222+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:05:42.245+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:05:42.241+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:05:42.247+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:05:42.266+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-07T10:06:12.397+0000] {processor.py:157} INFO - Started process (PID=3809) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:06:12.398+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:06:12.400+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:06:12.400+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:06:12.423+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:06:12.418+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:06:12.424+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:06:12.441+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.048 seconds
[2023-12-07T10:06:42.584+0000] {processor.py:157} INFO - Started process (PID=3817) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:06:42.585+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:06:42.587+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:06:42.587+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:06:42.612+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:06:42.607+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:06:42.614+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:06:42.632+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.051 seconds
[2023-12-07T10:07:12.746+0000] {processor.py:157} INFO - Started process (PID=3825) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:07:12.747+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:07:12.749+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:07:12.749+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:07:12.770+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:07:12.766+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:07:12.772+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:07:12.789+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-07T10:07:42.936+0000] {processor.py:157} INFO - Started process (PID=3833) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:07:42.937+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:07:42.939+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:07:42.939+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:07:42.962+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:07:42.958+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:07:42.964+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:07:42.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.047 seconds
[2023-12-07T10:08:13.099+0000] {processor.py:157} INFO - Started process (PID=3841) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:08:13.100+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:08:13.103+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:08:13.102+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:08:13.124+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:08:13.120+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:08:13.126+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:08:13.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-07T10:08:43.307+0000] {processor.py:157} INFO - Started process (PID=3849) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:08:43.308+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:08:43.311+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:08:43.310+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:08:43.332+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:08:43.328+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:08:43.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:08:43.351+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-07T10:09:13.474+0000] {processor.py:157} INFO - Started process (PID=3857) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:09:13.475+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:09:13.477+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:09:13.477+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:09:13.497+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:09:13.494+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:09:13.498+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:09:13.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.044 seconds
[2023-12-07T10:09:43.663+0000] {processor.py:157} INFO - Started process (PID=3865) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:09:43.664+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:09:43.667+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:09:43.666+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:09:43.689+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:09:43.685+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:09:43.690+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:09:43.706+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.046 seconds
[2023-12-07T10:10:13.832+0000] {processor.py:157} INFO - Started process (PID=3873) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:10:13.833+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:10:13.836+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:10:13.835+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:10:13.861+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:10:13.857+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:10:13.863+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:10:13.880+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.052 seconds
[2023-12-07T10:10:44.029+0000] {processor.py:157} INFO - Started process (PID=3881) to work on /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:10:44.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/fundamental_data_pipeline.py for tasks to queue
[2023-12-07T10:10:44.033+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:10:44.033+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:10:44.057+0000] {logging_mixin.py:154} INFO - [2023-12-07T10:10:44.052+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/fundamental_data_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/fundamental_data_pipeline.py", line 11, in <module>
    from libs.financials_api_get import get_fundemental_data
ModuleNotFoundError: No module named 'libs'
[2023-12-07T10:10:44.059+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/fundamental_data_pipeline.py
[2023-12-07T10:10:44.078+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/fundamental_data_pipeline.py took 0.052 seconds
